name: IFARHU DTI Blog
description:  Blog de la Dirección de Tecnología Informática
categories: ["Tecnologia", "Tutoriales", "Innovacion"]

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

baseurl: /

site:
  url:
    - /

permalink: /:year/:month/:title/
owner:
    name: IFARHU
    twitter: IFARHU
    github: /IFARHU/
    disqus_shortname: dti-blog

ga_id: UA-62484137-3
ga_username: #

exclude:
  - node_modules
