name: What's new
description:  IFARHU
categories: ["Tech News", "Tutorials"]

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: /

site:
  url:
    - /

permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: /IFARHU/
    disqus_shortname: #

ga_id: #
ga_username: #

exclude:
  - node_modules
